version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  gateway:
    image: asifmahmoud414/mock-gateway:latest
    restart: always

  server:
    image: ${DOCKER_IMAGE_SERVER}
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      GATEWAY_URL: http://gateway:9000
      CALLBACK_BASE_URL: ${SERVER_PUBLIC_URL}
      HOLD_TTL_SECONDS: ${HOLD_TTL_SECONDS}
      CLIENT_URL: ${CLIENT_PUBLIC_URL}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"

  client:
    image: ${DOCKER_IMAGE_CLIENT}
    restart: always
    ports:
      - "80:80"

volumes:
  pgdata:
  redisdata:
